<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        class MyPromise {
            constructor(executor) {//executor是必须传入的参数，是实际运用中需要异步执行的函数
                this.status = 'pending';
                this.value = undefined;
                this.resolveArr = [];//用来装.then中成功的回调函数，不止一个所以用数组
                this.rejectArr = [];//用来装.then中失败的回调函数，不止一个所以用数组
        
                let change = (status, value) => {//作为改变实例状态的一个函数
                    if (this.status !== 'pending') return;//只能改变一次所以若不为pending就不能继续
                    this.value = value;
                    this.status = status;
                    let fnArr = status === 'resolved' ? this.resolveArr : this.rejectArr;//是成功还是失败的回调？
                    fnArr.forEach(item => {
                        if (typeof item !== 'function') return;
                        item(this.value);//以executor中对resolve或者reject传入的参数作为回调函数的参数进行执行
                    });
                };
                let resolve = result => {
                    if (this.resolveArr.length > 0) {//若已经执行了.then放了回调函数才执行
                        change('resolved', result);
                        return;
                    }
                    let delayTimer = setTimeout(_ => {//若没有执行回调函数就利用一个定时器去模拟微任务的实现让.then先执行
                        change('resolved', result);
                        clearTimeout(delayTimer);//清除计时器
                    }, 0);
                };
                let reject = reason => {
                    if (this.rejectArr.length > 0) {
                        change('rejected', reason);
                        return;
                    }
                    let delayTimer = setTimeout(_ => {
                        change('rejected', reason);
                        clearTimeout(delayTimer);
                    }, 0);
                };
        
                try {//若executor本身执行不出错才会看executor中是执行的resolve还是reject
                    executor(resolve, reject);
                } catch (err) {//若本身执行出错了就会直接执行reject并传入出错的信息
                    reject(err.message);
                }
            }
        
            then(resolveFn, rejectFn) {
                // 如果传递的参数不是函数（NULL/不传递），我们让成功或者失败顺延
                if (typeof resolveFn !== 'function') {
                    resolveFn = result => {
                        return result;//如果是成功的回调函数没传直接把result参数传递即可
                    };
                }
                if (typeof rejectFn !== 'function') {
                    rejectFn = reason => {
                        return MyPromise.reject(reason);//如果是失败的回调函数没传就静态生成一个reject状态的promise实例
                    };
                }
                //为了满足回调函数的执行结果会对.then状态造成影响的效果，采用了闭包的处理机制，把新生成的实例的resolve，reject方法和resolverFn放在一个匿名函数中再放进resolverArr，从而通过识别resolverFn的执行结果选择执行resolve或者reject
                return new MyPromise((resolve, reject) => {
                    //注意这里的this指向的是上一次的promise实例，记住，函数的作用域永远是在定义的时候确定的，哪怕是在参数里
                    //因为这是箭头函数没有this所以向上找到上一次new生成的promise对象
                    this.resolveArr.push(result => {//
                        try {//若resolverFn执行成功
                            let x = resolveFn(result);
                            if (x instanceof MyPromise) {//若返回一个Promise实例会根据这个实例的状态来执行resolve或者是reject
                                x.then(resolve, reject);
                                return;
                            }
                            resolve(x);
                        } catch (err) {//若resolverFn执行失败
                            reject(err.message);
                        }
                    });
                    console.log(this);
                    this.rejectArr.push(reason => {//原理同上
                        try {
                            let x = rejectFn(reason);
                            if (x instanceof MyPromise) {
                                x.then(resolve, reject);
                                return;
                            }
                            resolve(x);
                        } catch (err) {
                            reject(err.message);
                        }
                    });
                });
            }
        
            // MyPromise.prototype.catch(fn) === MyPromise.prototype.then(null,fn)
            catch(rejectFn) {
                return this.then(null, rejectFn);
            }
        
            /* 静态方法 */
            static resolve(result) {//用来实现MyPromise.resolve(100)返回一个状态为成功的MyPromise实例
                return new MyPromise(resolve => {
                    resolve(result);
                });
            }
            static reject(reason) {
                return new MyPromise((_, reject) => {
                    reject(reason);
                });
            }
        
            static all(arr) {
                return new MyPromise((resolve, reject) => {
                    let index = 0,
                        results = [];
                    for (let i = 0; i < arr.length; i++) {
                        let item = arr[i];
                        if (!(item instanceof MyPromise)) continue;
                        item.then(result => {
                            index++;
                            results[i] = result;
                            if (index === arr.length) {
                                resolve(results);
                            }
                        }).catch(reason => {
                            // 只要有一个失败，整体就是失败
                            reject(reason);
                        });
                    }
                });
            }
        }
        
        let a = new MyPromise(function(resolve,reject){
            resolve(10);
        });
        a.then((result)=>{
            console.log(result);
        });
        </script>
</body>
</html>